version: "3"
services:
  zookeeper:
    image: 'wurstmeister/zookeeper:3.4.6'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-1:
    image: 'wurstmeister/kafka:2.12-2.1.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=192.168.1.66
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_offsets_topic_replication_factor=1
      - KAFKA_CREATE_TOPICS=SUO_VISIT_TEST:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka/1:/kafka
    depends_on:
      - zookeeper